services:
  - type: web
    name: salon-app-backend
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node src/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
